/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Wire type discriminant as seen by JS.
 *
 * 0 = Varint, 1 = Fixed64, 2 = Bytes (length-delimited), 5 = Fixed32.
 */
export const WIRE_VARINT: number
export const WIRE_FIXED64: number
export const WIRE_BYTES: number
export const WIRE_FIXED32: number
/**
 * A single decoded field handed back to JS.
 *
 * Exactly one of the value fields is populated, selected by `wireType`.
 * Varint/Fixed64 values are returned as `BigInt` to preserve all 64 bits.
 */
export interface DecodedField {
  fieldNumber: number
  wireType: number
  /** Present when wireType is Varint (0) or Fixed64 (1). */
  varint?: bigint
  /** Present when wireType is Fixed32 (5). */
  fixed32?: number
  /** Present when wireType is Bytes (2). */
  bytes?: Buffer
}
/** A field to encode, supplied by JS. Populate the value matching `wireType`. */
export interface FieldInput {
  fieldNumber: number
  wireType: number
  varint?: bigint
  fixed32?: number
  bytes?: Buffer
}
/**
 * Decode a protobuf buffer into a flat list of fields (no recursion).
 *
 * Length-delimited fields are returned as raw bytes; re-call `decodeFields`
 * on them if you know they are submessages.
 */
export declare function decodeFieldsJs(buf: Buffer): Array<DecodedField>
/** Encode a list of fields into a protobuf buffer. */
export declare function encodeFieldsJs(fields: Array<FieldInput>): Buffer
/**
 * A node in the recursive decode tree, as JSON-friendly data for JS.
 *
 * `kind` is one of: "varint" | "fixed64" | "fixed32" | "bytes" | "message".
 */
export interface TreeNode {
  fieldNumber: number
  kind: string
  varint?: bigint
  fixed32?: number
  bytes?: Buffer
  message?: Array<TreeNode>
}
/**
 * Recursively decode `buf` into a tree, descending into submessages, bounded
 * by `maxDepth`. Exceeding the depth throws instead of overflowing the stack.
 */
export declare function decodeTreeJs(buf: Buffer, maxDepth: number): Array<TreeNode>
/** ZigZag-encode a signed 64-bit integer (for sint32/sint64). */
export declare function zigzagEncode(value: bigint): bigint
/** ZigZag-decode back to a signed 64-bit integer. */
export declare function zigzagDecode(value: bigint): bigint
